version: "3.7"

services:
  client:
    build: .
    env_file:
      - commands.env
    ports:
      - "8000:8000"
    networks:
      - mynet

  db:
    image: postgres
    volumes:
      - ./.db/postgres/data:/var/lib/postgresql/data
    env_file:
      - db.env
    ports:
      - "5432:5432"
    networks:
      - mynet

networks:
  mynet:
    driver: bridge