version: "3.7"

services:
  client:
    build: .
    env_file:
      - cfg/commands.env
    ports:
      - "8000:8000"
    links:
      - db

  db:
    image: postgres
    volumes:
      - ./.db/postgres/data:/var/lib/postgresql/data
    env_file:
      - cfg/db.env
    ports:
      - "5432:5432"
