version: "3.7"

services:
  client:
    build: .
    env_file:
      - cfg/commands.env
    ports:
      - "8000:8000"
    links:
      - db

  db:
    image: postgres
    volumes:
      - ./.db/postgres/data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
